---
- hosts: localhost
  tasks:
  - name: install python and pip
    yum:
      name: python-pip
      state: present
  - name: Install boto3 for Ansible Lookup Plugin to work
    pip:
      name: boto
