---
# tasks file for tomcat
- name: Check Tomcat already exists or not
  stat:
    path: "{{ tomcat_download_directory }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
  register: check_tomcat_existence
- name: Print tomcat tar file exists or not
  debug:
    msg: "{{ check_tomcat_existence }}"
- name: Download Apache Tomcat 9
  get_url:
    url: "{{ tomcat_download_url }}"
    dest: "{{ tomcat_download_directory }}"
    mode: '0777'
  when: not check_tomcat_existence.stat.exists
- name: unarchive Apache tomcat
  unarchive:
    src: "{{ tomcat_download_directory }}/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "{{ tomcat_download_directory }}"
    remote_src: yes
- name: Create Tomcat user and Group
  user:
    name: tomcat
    comment: user for tomcat
- name: Change owner ship for tomcat
  file:
    path: /opt/apache-tomcat-{{ tomcat_version }}
    state: directory
    recurse: yes
    owner: tomcat
    group: tomcat
    mode: '0755'
- name : Tomcat template to /etc/systemd/system/
  template:
    src: templates/tomcat.service.j2 
    dest: /etc/systemd/system/tomcat.service
    mode: 0755
- name: just force systemd to reread configs (2.4 and above)
  systemd:
    daemon_reload: yes
- name: enable tomcat startup
  service:
    name: tomcat
    state: started
